### ISSUE TITLE
Investigate/Integrate ruff

### ISSUE THREAD

**Issue by chris34** [inyokaproject/inyoka#1273]
https://github.com/astral-sh/ruff

Seems to be fast and a replacement for flake and isort
(but not for black?)

**Comment by chrysle** [comment]
There actually isn't any documentation on linting, right now. Seemingly `isort` and `flake8` have been used, but it might be reasonable to agree on a linting procedure and document that, and probably integrate a plugin like [pylint-django](https://pypi.org/project/pylint-django/).

**Comment by encbladexp** [comment]
Personally I am happy with just ruff. Does Django have any configuration deviations from its standards?

**Comment by chrysle** [comment]
> Personally I am happy with just ruff.

Fine with me, too.

> Does Django have any configuration deviations from its standards?

I could only find something on [code style for Django itself](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/).

**Comment by encbladexp** [comment]
So they are using the black standard configuration, at least if I didn't overlook something. The mention to use isort and black as pre-commit hook, in addition they mention a 88 character limit.

From my POV: Apply it to our code base as well. We like to stay aligned to Django as much as possible, so let's just do it the same way, and not overthink such stuff.
