### ISSUE TITLE
Version schema

### ISSUE THREAD

**Issue by chris34** [inyokaproject/inyoka#1313]
At the moment Inyoka still uses zero-based versioning. It's questionable whether this fits the project. Some ideas include:

 -  use 1.0 for public release?
 -  switch to calver?
 -  include Django-version in major or minor?

**Comment by encbladexp** [comment]
Some addition: We could also integrate e.g. setuptools.scm, so get the version out of git or something like (would that be helpful, after all?).

**Comment by chrysle** [comment]
> (would that be helpful, after all?).

Spares some effort that is required to manually update the version number in the source code. I'd be in favor.

**Comment by chris34** [comment]
just to be clear: do i see it right that setuptools.scm will only extract the version from a git tag? So the git tag i have to do on my own?

At the moment we still have bump2version (see [release procedure](https://github.com/inyokaproject/inyoka/blob/bd6f7c4a12334384c7ba8fea40ea373a9edc5530/docs/release_procedure.rst#L71)) So i dont have to do the math in my brain :brain:.

https://github.com/c4urself/bump2version is no longer maintained and recommends https://github.com/callowayproject/bump-my-version

bump-my-version looks quite sophisticated. (At least for semver and calver…)

**Comment by encbladexp** [comment]
Exactly, you just tag in git, and setuptools.scm will get the version information out of git. If you build a wheel package with it, its tagged with the version, and you could use the standard packaging stuff to retrieve the previously tagged version. 🪄

**Comment by chris34** [comment]
so if i download a tarball version for a release from github, i will not know from a file which version I'm currently looking at? Dont know if i like that. I'm still more on the bump-my-version side (where the version is automatically incremented according to a scheme, updated in a file and also a git commit with a tag is created).

--------

And to come back to the topic: I would even consider calver. The only drawback i see is that a way out is quite hard. (only with a  jump from a 202x to 3000 version)

Feel free to give counter arguments.

**Comment by chrysle** [comment]
> so if i download a tarball version for a release from github, i will not know from a file which version I'm currently looking at?

[It's possible to configure `setuptools_scm` to create a file containing the version.](https://setuptools-scm.readthedocs.io/en/latest/usage/#version-files).

**Comment by chris34** [comment]
https://github.com/inyokaproject/inyoka/pull/1344 is now a proposal to use bump-my-version (i found it's documentation way more better than stuptools_scm)

The schema there is now `{major}.{django}.{patch}`.

 - Major and patch will be increased normally.
 - The used django version is now in between (where normally the minor version is). An example: if inyoka uses django 4.2 it has the scheme `x.42.y`.

**Comment by encbladexp** [comment]
I thought more about directly using the Django Version, except the Patch Level. As an example Django 4.2 would be Inyoka 4.2, the deviation is the Patch Level. If we are honest: We only port Inyoka every now and then to new releases of Django, this could also be used to introduce new features, everything else are just patches.

**Comment by chris34** [comment]
> We only port Inyoka every now and then to new releases of Django, [...]
> this could also be used to introduce new features

To be honest i wouldn't want to wait at least until April (the release of the next Django LTS 5.2) to merge a new feature in Inyoka. And if we need more time for porting to a newer Django version, that would be even later to ship a new feature...

We dont develop a library, have no LTS status to maintain. We just need to make sure to provide upwards DB migration without a 'hard stop point'.

Most of the time it's more like 'we have tests, looks good on staging, lets ship it as soon as possible (otherwise it's never)'.

(You can also call it somehow 'rolling'. That's somehow also the background that i thought about calver. Additionally, people can see, if they still run an Inyoka version from last year.)

**Comment by encbladexp** [comment]
I am fine with that too, just make a decision, document it and we fixed that topic :D

**Comment by chris34** [comment]
> I am fine with that too, just make a decision, document it and we fixed that topic :D

I'll just merge the PR for now, so i dont have to rebase for a new Inyoka version.

If someone sees an mistake or enhancements, feel free to open a follow-up issue or PR.
