### ISSUE TITLE
Publish documentation on project website

### ISSUE THREAD

**Issue by chrysle** [inyokaproject/inyoka#1327]
With the OSS release upcoming, it should be worthwhile to publish the existing documentation on the project's domain _inyokaproject.org_, which currently redirects to the organization's GitHub page. An easy option would be to [make use of Read The Docs](https://docs.readthedocs.io/en/stable/tutorial/index.html), which also allows for [custom domains](https://docs.readthedocs.io/en/stable/guides/custom-domains.html).

**Comment by encbladexp** [comment]
Is it worth thinking about a migration from RST => Markdown?

For me just dropping an automatically generated HTML thingy on GH pages seems to be what we should do. I agree that we should not use the included wiki of GH, just in case we want or need to migrate away.

**Comment by chris34** [comment]
> Is it worth thinking about a migration from RST => Markdown?

Spontaneously, we could just enable Markdown in sphinx additionally

https://www.sphinx-doc.org/en/master/usage/markdown.html#markdown

As both Makdown and RST can coexist → we don't even have to migrate everything now (pandoc could make the migration easier nonetheless).

**Comment by encbladexp** [comment]
That is a great idea 👍

**Comment by chris34** [comment]
I'll close this, as

 - https://doc.inyokaproject.org/ (even with https) now works via github pages
 - markdown support is enabled in #1342
