### ISSUE TITLE
Installation instructions outdated

### ISSUE THREAD

**Issue by chrysle** [inyokaproject/inyoka#1328]
I just set up my local Inyoka instance and discovered a few mistakes in the docs.

- The `nodejs-legacy` package does no longer exist, and seems to be obsolete; at least everything seems to work right now
- `libzmq-dev` is now `libzmq3-dev`
- Applying the migrations failed with connection error; through https://github.com/inyokaproject/inyoka/blob/024df9cfea172c973e69b0c3b73a47abd465c10a/.github/workflows/test.yml#L106-L114 I got the idea to set the authentication method for the Unix domain socket connection in `/etc/postgresql/16/main/pg_hba.conf` to `trust`; seems to work now. This might also be accomplished via [user name maps](https://www.postgresql.org/docs/current/auth-username-maps.html#AUTH-USERNAME-MAPS), I guess

**Comment by encbladexp** [comment]
Also related to #1339

**Comment by encbladexp** [comment]
I made a PR for the outdated Debian/Ubuntu package list, PostgreSQL on the other side is not our topic. It will work in its default configuration according to my knowledge, trust should not be required if a password is used.

**Comment by encbladexp** [comment]
Fixed  through #1356
