### ISSUE TITLE
Installation failed on Ubuntu 22.04 and Debian 12

### ISSUE THREAD

**Issue by henrystauder** [inyokaproject/inyoka#1339]
hi Team,

by try to install the Inyoka (inyoka-staging) portal to an Ubuntu 22.04 or Debian 12, the installation failed in both systems by using the manual "installation.rst".

In first the needed dependencies are running in error
`$  sudo apt-get install git nodejs-legacy libxml2-dev libxslt1-dev libzmq-dev zlib1g-dev libjpeg-dev uuid-dev libfreetype6-dev libpq-dev build-essential libpq-dev libffi-dev python3-dev`

nodejs-legacy  
libzmq-dev
are in both  destributions  (Ubuntu 22.04 and Debian 12) not avalible.

by starting 
`   $ pip install -r extra/requirements/development.txt`
the installtion will break in Ubuntu during the download. (this has been tested in several sessions of new install of OS)
In Debian the information appears that the Python version must be selected. In this situation the adding of Python from Repository doesnt change the result.

Installation has been done in Debian with different versions of Python but no success.

Test installations has been done on a physical maschine ( Ubuntu and Debian) as well in lxc 's of ProxMox.

And  >> NO Docker is neither an option nor desired.

**Comment by encbladexp** [comment]
These Installations Docs are about 4 year old. However, it does not mean you are forced to use Docker.

You could grab the `Dockerfile` from [docker-setup](https://github.com/inyokaproject/docker-setup), it contains the commands we used to build our images, and these commands will also work on Ubuntu 22.04 and Debian 12, as the image is based on them too.

Could you test:
```
apt-get install -y --no-install-recommends libxml2-dev libxslt1-dev zlib1g-dev \
 libjpeg-dev uuid-dev libfreetype6-dev libpq-dev build-essential libpq-dev \
 libffi-dev libmagic1 postgresql-client
```

You did `pip install` in a Virtualenv? We expect Python 3.12 these days, maybe older versions will work, but 3.12 is also used for our docker builds.

Of course, I will worry about updating the docs. We are planning to move them to a new / better location anyways ;)

**Comment by encbladexp** [comment]
I just made a PR to fix at least the Debian/Ubuntu packages, these had been outdated for a long time.

The Python package related issues are under clarification right now. Please hold the line.

**Comment by chris34** [comment]
As a result of https://github.com/inyokaproject/inyoka/pull/1362, the staging branch now contains multiple requirement-files for all supported python-versions. The requirement file that fits with your local python version should now work with pip (we even test that in the CI after every change).

As a sidenote: Without docker, you will also need to make sure two celery-services run always in the background (e.g. with a systemd-unit). The commands for the [celeryworker](https://github.com/inyokaproject/docker-setup/blob/main/docker-compose.yaml#L76) and the [celerybeat](https://github.com/inyokaproject/docker-setup/blob/main/docker-compose.yaml#L80) in the docker files can be a starting point. 

Feel free to reopen this issue or open a new one, if there are more questions.
